### ISSUE TITLE
Remove js_style dependency from releases

### ISSUE THREAD

**Issue by jaapb** [janestreet/ppx_base#1]
Would it be possible to get the js_style dependency removed from full releases? It seems only useful in a development environment, and it saves packaging efforts down the line...

**Comment by v-gb** [comment]
I don't know what a "full release" is, but it is true that ppx_js_style could, in principle, be a dependency only for development of libraries preprocessed by ppx_base, not for building debian packages of such libraries.

That said the only difference between ppx_base and ppx_base without ppx_js_style, is ppx_js_style itself and this octavius library (which itself depends on just the stdlib), both of which should be straightforward to package. Assuming dune can even express this, which I don't know to be true,  having a special build mode just for packaging means an untested build mode, which is not great if the benefit is low. Is this really worth? 

@xclerc @jeremiedimino perhaps you can provide some context about whether we do things like this elsewhere, or we explicitly avoid doing this, or something else?

**Comment by ghost** [comment]
There are things we could do but that's quite a lot of work.

@jaapb, here is a low-tech solution to do exactly what you want:

```
$ sed -i s/ppx_js_style// src/dune
```

**Comment by jaapb** [comment]
@jeremiedimino Yes, that's what the pkgsrc package does at the moment. I'd hoped to be able to move that solution upstream for releases, but if that is too much work, or otherwise not worth it, then I can just keep the pkgsrc patches in place.

Thanks for considering the problem!

**Comment by v-gb** [comment]
I took a look at pkgsrc: [list of patches](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/ocaml-ppx_base/patches/), [patch1](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/ocaml-ppx_base/patches/patch-ppx__base.opam?rev=1.1&content-type=text/x-cvsweb-markup), [patch2](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/ocaml-ppx_base/patches/patch-src_dune?rev=1.1&content-type=text/x-cvsweb-markup).

So it's a change to the dune file, and the opam file. And because they are patches to the repo (as opposed to transformations with `sed` or the likes), I imagine it conflicts from times to times.

Also many other dune files get patched to remove the flags intended for ppx_js-style, like [this one](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/ocaml-core_kernel/patches/patch-thread__pool__cpu__affinity_src_dune?rev=1.2&content-type=text/x-cvsweb-markup). 

Given that last point, it seems that if we wanted to support not using ppx_js_style, the simplest thing would be to have a variation of ppx_js_syle which accepts command line arguments but otherwise does nothing. But at that point it's one package with this hypothetical solution vs two packages if the ppx_base is built as normal (ppx_js_style + octavius).

**Comment by ghost** [comment]
BTW, at a high-level there is something a bit annoying with all this: if people install a `ppx_base` that doesn't have the proper `ppx_js_style`, then when they write a PR to one of our packages they won't get the errors from `ppx_js_style`. 

Both `ppx_js_style` and `octavius` are pretty small dependencies. Is it really worth complicating things to get rid of them?

**Comment by v-gb** [comment]
I'm going to close this, given that it seems that excluding ppx_js_style by construction is a similar amount of work to packaging it, and has the undesirable implication that Jeremie mentioned.
